services:
  postgres:
    image: postgres:17
    container_name: securevault-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: securevault
      POSTGRES_USER: securevault
      POSTGRES_PASSWORD: securevault

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: